version: '3'
services: 

  web:

      build: .
      container_name: cat_db
      volumes: 
      - .:/app
      - static:/app/static_cdn
      - media:/app/media_cdn
      depends_on: 
          - db
      ports: 
        - 8000:8000
      command: bash -c "python ./app/manage.py makemigrations && python ./app/manage.py migrate && python ./app/manage.py runserver 0.0.0.0:8000"

  db:
      build: ./postgres
      restart: unless-stopped
      environment:   # will be used by the init script
            LC_ALL: C.UTF-8
            POSTGRES_USER: myprojectuser
            POSTGRES_PASSWORD: testing321
            POSTGRES_DB: myproject
      volumes:
          - pgdata:/var/lib/postgresql/data/
volumes:
  pgdata:
  media:
  static:

