version: '3'
services: 

  web:

      build: .
      container_name: great
      volumes: 
      - .:/app
      - static:/app/static_cdn
      - media:/app/media_cdn
      depends_on: 
          - postgres
      expose: 
        - 8000
      command: bash -c "python ./app/manage.py collectstatic --no-input && python ./app/manage.py makemigrations && python ./app/manage.py migrate && gunicorn --workers=3 projectname.wsgi -b 0.0.0.0:8000"

  postgres:
      build: ./postgres
      restart: unless-stopped
      expose:
        - "5432"
      environment:   # will be used by the init script
            LC_ALL: C.UTF-8
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassowrd.
            POSTGRES_DB: mydb
      volumes:
          - pgdata:/var/lib/postgresql/data/  
volumes:
  pgdata:
  media:
  static:

